# Generated by Django 3.2.5 on 2021-11-22 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_author_image'),
        ('category', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('content', models.TextField()),
                ('banner', models.ImageField(upload_to='')),
                ('discountFactor', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1)])),
                ('appliedAuthors', models.ManyToManyField(to='login.Author')),
                ('appliedBooks', models.ManyToManyField(to='category.Book')),
                ('appliedPublisher', models.ManyToManyField(to='login.Publisher')),
            ],
        ),
    ]
