# Generated by Django 3.2.5 on 2021-11-23 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_author_image'),
        ('category', '0008_auto_20211123_2029'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Sự kiện', 'verbose_name_plural': 'Quản lý sự kiện'},
        ),
        migrations.AlterField(
            model_name='event',
            name='appliedAuthors',
            field=models.ManyToManyField(blank=True, to='login.Author', verbose_name='Tác giả được áp dụng'),
        ),
        migrations.AlterField(
            model_name='event',
            name='appliedBooks',
            field=models.ManyToManyField(blank=True, to='category.Book', verbose_name='Sách được áp dụng'),
        ),
        migrations.AlterField(
            model_name='event',
            name='appliedPublisher',
            field=models.ManyToManyField(blank=True, to='login.Publisher', verbose_name='NXB được áp dụng'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(upload_to='', verbose_name='Banner sự kiện'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='Nội dung khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='discountFactor',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Tỷ lệ giảm giá(%)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên sự kiện'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(verbose_name='Ngày bắt đầu'),
        ),
    ]
