# Generated by Django 3.2.5 on 2022-01-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20220114_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='', verbose_name='Ảnh sự kiện'),
        ),
    ]
