# Generated by Django 3.2.5 on 2021-11-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_author_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'tác giả', 'verbose_name_plural': 'Quản lý tác giả'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'nhà xuất bản', 'verbose_name_plural': 'Quản lý nhà xuất bản'},
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(verbose_name='Giới thiệu về tác giả'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Hình ảnh tác giả'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên tác giả'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(verbose_name='Giới thiệu về nhà xuất bản'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên nhà xuất bản'),
        ),
    ]
