# Generated by Django 3.2.5 on 2021-11-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('EB', 'EBOOK'), ('NB', 'BOOK')], max_length=10)),
                ('language', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('genre', models.CharField(choices=[('CTPL', 'Chính trị pháp luật'), ('KHCNKT', 'Khoa học công nghệ - Kinh tế'), ('VHNT', 'Văn học nghệ thuật'), ('VHXHLS', 'Văn hóa xã hội - Lịch sử'), ('TTT', 'Truyện, tiểu thuyết'), ('TLTG', 'Tâm linh, tôn giáo'), ('STN', 'Sách thiếu nhi'), ('TT', 'Truyện tranh')], max_length=20)),
                ('rating', models.IntegerField()),
                ('author', models.ManyToManyField(to='login.Author')),
                ('publisher', models.ManyToManyField(to='login.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('pdfFile', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('createdAt', models.DateTimeField()),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creator', models.TextField()),
                ('books', models.ManyToManyField(to='category.Book')),
            ],
        ),
    ]
