# Generated by Django 3.2.5 on 2021-11-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_news_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('CTPL', 'Chính trị pháp luật'), ('KHCNKT', 'Khoa học công nghệ - Kinh tế'), ('VHNT', 'Văn học nghệ thuật'), ('VHXHLS', 'Văn hóa xã hội - Lịch sử'), ('GD', 'Giáo dục'), ('TL', 'Tâm lý'), ('TTT', 'Truyện, tiểu thuyết'), ('TLTG', 'Tâm linh, tôn giáo'), ('STN', 'Sách thiếu nhi'), ('TT', 'Truyện tranh')], max_length=20),
        ),
    ]
