# Generated by Django 3.2.5 on 2021-11-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='beingBorrowedQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
