# Generated by Django 3.2.5 on 2021-11-22 02:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_book_beingborrowedquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
