# Generated by Django 3.2.5 on 2021-11-22 03:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
