# Generated by Django 3.2.5 on 2021-11-23 13:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_author_image'),
        ('category', '0007_alter_collection_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'sách', 'verbose_name_plural': 'Quản lý sách'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'bộ sưu tập', 'verbose_name_plural': 'Quản lý bộ sưu tập'},
        ),
        migrations.AlterModelOptions(
            name='magazine',
            options={'verbose_name': 'tạp chí', 'verbose_name_plural': 'Quản lý tạp chí'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'tin tức', 'verbose_name_plural': 'Quản lý tin tức'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='login.Author', verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='book',
            name='beingBorrowedQuantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng đã mượn'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('CTPL', 'Chính trị pháp luật'), ('KHCNKT', 'Khoa học công nghệ - Kinh tế'), ('VHNT', 'Văn học nghệ thuật'), ('VHXHLS', 'Văn hóa xã hội - Lịch sử'), ('GD', 'Giáo dục'), ('TL', 'Tâm lý'), ('TTT', 'Truyện, tiểu thuyết'), ('TLTG', 'Tâm linh, tôn giáo'), ('STN', 'Sách thiếu nhi'), ('TT', 'Truyện tranh')], max_length=20, verbose_name='Thể loại'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=20, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='login.Publisher', verbose_name='Nhà xuất bản'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(verbose_name='Đánh giá'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=ckeditor.fields.RichTextField(verbose_name='Tóm tắt nội dung'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('EB', 'Sách điện tử'), ('NB', 'Sách giấy')], max_length=10, verbose_name='Loại sách'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='books',
            field=models.ManyToManyField(to='category.Book', verbose_name='Bao gồm'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='creator',
            field=models.CharField(max_length=255, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Bản mô tả'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pdfFile',
            field=models.FileField(upload_to='', verbose_name='File PDF'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='summary',
            field=models.TextField(verbose_name='Tóm tắt nội dung'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Nội dung bài viết'),
        ),
        migrations.AlterField(
            model_name='new',
            name='createdAt',
            field=models.DateTimeField(verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='new',
            name='summary',
            field=models.TextField(verbose_name='Tóm tắt nội dung'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
    ]
