# Generated by Django 3.2.5 on 2021-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20211123_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='brief_sum',
            field=models.CharField(default='abc', max_length=50, verbose_name='Tóm tắt ngắn gọn'),
        ),
        migrations.AddField(
            model_name='collection',
            name='creator_role',
            field=models.CharField(default='Thủ thư', max_length=255, verbose_name='Chức vụ'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='anh_bia.jpg', upload_to='', verbose_name='Ảnh bìa'),
        ),
    ]
