# Generated by Django 3.2.5 on 2021-12-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20211204_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='creator_image',
            field=models.ImageField(default='anh_nguoi_tao.jpg', upload_to='', verbose_name='Ảnh người tạo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='brief_sum',
            field=models.CharField(default='abc', max_length=255, verbose_name='Tóm tắt ngắn gọn'),
        ),
    ]
