# Generated by Django 3.2.5 on 2021-12-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_book_publishyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Bản điện tử', 'Sách điện tử'), ('Bản giấy', 'Sách giấy')], max_length=20, verbose_name='Loại sách'),
        ),
    ]
