# Generated by Django 3.2.5 on 2021-12-29 17:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_alter_book_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('summary', models.TextField(verbose_name='Tóm tắt nội dung')),
                ('createdAt', models.DateTimeField(verbose_name='Ngày tạo')),
                ('author', models.CharField(max_length=50, verbose_name='Tác giả')),
                ('image', models.ImageField(upload_to='', verbose_name='Hình ảnh')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Nội dung bài viết')),
            ],
            options={
                'verbose_name': 'bài đánh giá',
                'verbose_name_plural': 'Quản lý bài đánh giá',
            },
        ),
    ]
