# Generated by Django 3.2.5 on 2022-01-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0019_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='genre',
            field=models.CharField(choices=[('Time', 'Time'), ('Money', 'Money'), ('Economist', 'Economist'), ('Forbes', 'Forbes'), ('GQ', 'GQ'), ('Entrepreneur', 'Entrepreneur'), ('TheNewYorker', 'TheNewYorker'), ('Elle', 'Elle')], default='Time', max_length=50, verbose_name='Thể loại'),
            preserve_default=False,
        ),
    ]
