# Generated by Django 3.2.5 on 2021-11-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('emailAddress', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.CharField(choices=[(0, 'NOT ANSWER'), (1, 'ANSWERED')], default=0, max_length=30)),
            ],
        ),
    ]
