# Generated by Django 3.2.5 on 2021-11-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20211122_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('NOT ANSWER', 'NOT ANSWER'), ('ANSWERED', 'ANSWERED')], default='NOT ANSWER', max_length=30),
        ),
    ]
