# Generated by Django 3.2.5 on 2021-11-22 03:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
