# Generated by Django 3.2.5 on 2021-11-23 13:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20211123_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung phản hồi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emailAddress',
            field=models.CharField(max_length=100, verbose_name='Địa chỉ Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Họ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Nội dung câu hỏi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('NOT ANSWER', 'Chưa trả lời'), ('ANSWERED', 'Đã trả lời')], default='NOT ANSWER', max_length=30, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
    ]
