# Generated by Django 3.2.5 on 2021-11-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20211123_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'thư phản hồi', 'verbose_name_plural': 'Quản lý thư phản hồi'},
        ),
    ]
