# Generated by Django 3.2.5 on 2021-11-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membercard',
            old_name='borrowedBooks',
            new_name='beingBorrowedBooks',
        ),
        migrations.RenameField(
            model_name='membercard',
            old_name='maxNumOfBorrowedBooks',
            new_name='beingBorrowedBooksQuantity',
        ),
        migrations.RenameField(
            model_name='membercard',
            old_name='numOfBorrowedBooks',
            new_name='maxNumOfBooksToBorrow',
        ),
    ]
