# Generated by Django 3.2.5 on 2021-12-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercard',
            name='booksBeingBorrowed',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MemberCard',
        ),
    ]
