# Generated by Django 3.2.5 on 2021-11-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_auto_20211122_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membercard',
            old_name='beingBorrowedBooks',
            new_name='booksBeingBorrowed',
        ),
        migrations.RenameField(
            model_name='membercard',
            old_name='beingBorrowedBooksQuantity',
            new_name='maxNbOfBooksToBorrow',
        ),
        migrations.RenameField(
            model_name='membercard',
            old_name='maxNumOfBooksToBorrow',
            new_name='nbOfBooksBeingBorrowed',
        ),
    ]
