# Generated by Django 3.2.5 on 2021-11-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20211123_2029'),
        ('myaccount', '0003_auto_20211122_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercard',
            options={'verbose_name': 'thẻ thành viên', 'verbose_name_plural': 'Quản lý thẻ thành viên'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'người dùng', 'verbose_name_plural': 'Quản lý người dùng'},
        ),
        migrations.AlterField(
            model_name='membercard',
            name='booksBeingBorrowed',
            field=models.ManyToManyField(to='category.Book', verbose_name='Những cuốn sách đang mượn'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='maxNbOfBooksToBorrow',
            field=models.IntegerField(verbose_name='Số lượng sách mượn tối đa'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='nbOfBooksBeingBorrowed',
            field=models.IntegerField(verbose_name='Số lượng sách đang mượn'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='numOfFault',
            field=models.IntegerField(verbose_name='Số lỗi đã vi phạm'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='registerDate',
            field=models.DateTimeField(null=True, verbose_name='Ngày đăng ký'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='servicePlan',
            field=models.CharField(choices=[('NE', 'Chưa đăng ký'), ('MB', 'Thẻ tháng thường'), ('AB', 'Thẻ năm thường'), ('MV', 'Thẻ tháng VIP'), ('AV', 'Thẻ năm VIP')], max_length=30, verbose_name='Gói dịch vụ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa chỉ nhà'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailAddress',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identificationCard',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Số CMND'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Họ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='memberCard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myaccount.membercard', verbose_name='Thẻ đã đăng ký'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Mật khẩu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên đăng nhập'),
        ),
    ]
