# Generated by Django 3.2.5 on 2021-12-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_book_createdat'),
        ('myaccount', '0003_customer_membercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày mượn')),
                ('expired_date', models.DateTimeField(verbose_name='Ngày hết hạn mượn')),
                ('status', models.CharField(choices=[('Bình thường', 'Bình thường'), ('Quá hạn mức 1', 'Quá hạn mức 1'), ('Quá hạn mức 2', 'Quá hạn mức 2')], max_length=30, verbose_name='Trạng thái mượn')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_list', to='category.book', verbose_name='Sách mượn')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_list', to='myaccount.customer', verbose_name='Người mượn')),
            ],
        ),
    ]
