# Generated by Django 3.2.5 on 2021-12-08 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myaccount', '0004_auto_20211124_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Họ')),
                ('firstName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tên')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Tên đăng nhập')),
                ('password', models.CharField(max_length=50, verbose_name='Mật khẩu')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('emailAddress', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Địa chỉ email')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa chỉ nhà')),
                ('identificationCard', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Số CMND')),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Số điện thoại')),
                ('memberCard', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myaccount.membercard', verbose_name='Thẻ đã đăng ký')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'người dùng',
                'verbose_name_plural': 'Quản lý người dùng',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
