# Generated by Django 3.2.5 on 2021-12-23 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Thành phố'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='orderedbooks',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày trả sách'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedbooks',
            name='status',
            field=models.CharField(choices=[('Bình thường', 'Bình thường'), ('Quá hạn mức 1', 'Quá hạn mức 1'), ('Quá hạn mức 2', 'Quá hạn mức 2'), ('Đã trả', 'Đã trả')], max_length=30, verbose_name='Trạng thái mượn'),
        ),
    ]
